import = ["~/.dotfiles/alacritty/catppuccin-frappe.toml"]
live_config_reload = true

[terminal]
osc52 = "OnlyCopy"

[env]
TERM = "xterm-256color"

[mouse]
hide_when_typing = true

[window]
dimensions = { columns = 192, lines = 48 }
padding = { x = 4, y = 0 }
decorations = "Buttonless"

[font]
size = 16.0
offset = { x = 0, y = 1 }

normal = { family = "FiraCode Nerd Font", style = "Medium" }
bold = { family = "FiraCode Nerd Font", style = "Bold" }
italic = { family = "FiraCode Nerd Font", style = "Medium Italic" }
bold_italic = { family = "FiraCode Nerd Font", style = "Bold Italic" }
