[ -z $PS1 ] && return

settings=$(dirname $BASH_SOURCE)

source $settings/bash.common
source $settings/bash.prompt

case $(uname -s) in
  Linux)
    source $settings/path.linux
    source $settings/env.linux
    ;;
  Darwin)
    source $settings/path.macos
    source $settings/env.macos
    ;;
esac
