[ -z $PS1 ] && return

settings=$(dirname ${(%):-%x})

source $settings/zsh.common
source $settings/zsh.prompt

case $(uname -s) in
  Linux)
    source $settings/path.linux
    source $settings/env.linux
    ;;
  Darwin)
    source $settings/path.macos
    source $settings/env.macos
    ;;
esac
