" Options
set nocompatible
set encoding=utf-8
set background=dark
set mouse=a
set cursorline
set modelines=0
set nobackup
set nowritebackup
set noswapfile
"set nowrap
set history=50
set number
set numberwidth=5
set autoindent
set smartindent
set ruler
set incsearch
set hlsearch
set autoread
set visualbell
set showmatch
set showcmd
set tabstop=2
set softtabstop=2
set shiftwidth=2
set expandtab
set nosmarttab
"set textwidth=80
set colorcolumn=80
set ignorecase
set smartcase
set splitright

syntax on

" Vundle
filetype off

set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

Plugin 'gmarik/Vundle.vim'
Plugin 'tpope/vim-sensible'
Plugin 'tpope/vim-surround'
Plugin 'tpope/vim-fugitive'
Plugin 'kien/ctrlp.vim'
Plugin 'fholgado/minibufexpl.vim'
Plugin 'scrooloose/syntastic'
Plugin 'scrooloose/nerdtree'
Plugin 'Xuyuanp/nerdtree-git-plugin'
Plugin 'rking/ag.vim'
Plugin 'moll/vim-bbye'
Plugin 'vim-scripts/verilog_systemverilog_fix'

call vundle#end()

filetype plugin indent on

" Trim whitespace
autocmd BufWritePre * :%s/\s\+$//e

" Highlight todos
call matchadd('Todo', '\s\+$')
call matchadd('Todo', 'TODO')
call matchadd('Todo', 'TODO:')
call matchadd('Todo', 'FIXME')
call matchadd('Todo', 'FIXME:')

" File explorer style
let g:netrw_liststyle=1

" Buffer navigation
nnoremap <C-L> :bnext<CR>
nnoremap <C-H> :bprevious<CR>

" Buffer resizing
nnoremap <C-W><C-K> :exe "resize +5"<CR>
nnoremap <C-W><C-J> :exe "resize -5"<CR>
nnoremap <C-W><C-L> :exe "vertical resize +5"<CR>
nnoremap <C-W><C-H> :exe "vertical resize -5"<CR>

" Close buffer without closing window
nnoremap <C-X> :Bdelete<CR>

" Colors
colorscheme molokai

" Use ii instead of ESC
imap ii <Esc>

" Status line
set statusline=%<\ %n:%f\ %m%r
set statusline+=%{fugitive#statusline()}%#warningmsg#%{SyntasticStatuslineFlag()}%*
set statusline+=%=line:\ %l\/%L,\ col:\ %c%V\ (%P)\ 0x%B

" NerdTree
nnoremap <C-N> :NERDTreeToggle<CR>
autocmd StdinReadPre * let s:std_in=1
autocmd VimEnter * if argc() == 0 && !exists("s:std_in") | NERDTree | endif
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTreeType") && b:NERDTreeType == "primary") | q | endif

" Syntastic
let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

" MiniBufExpl colors
hi MBENormal               ctermfg=248
hi MBEChanged              ctermfg=208
hi MBEVisibleNormal        ctermfg=81
hi MBEVisibleChanged       ctermfg=201
hi MBEVisibleActiveNormal  ctermfg=226
hi MBEVisibleActiveChanged ctermfg=201
