if [ -z $PS1 ]; then
   return
fi

settings=$(dirname $BASH_SOURCE)

source $settings/bash.common
source $settings/bash.prompt

case $(uname -s) in
  Linux)
    source $settings/path.linux
    source $settings/bash.linux
    ;;
  Darwin)
    source $settings/path.macos
    source $settings/bash.macos
    ;;
esac
